collections_config:
  posts:
    path: content/posts
    output: false
    new_preview_url: /previewer/ # Also use the previewer page to preview new, unsaved files
    _enabled_editors:
      - visual
      - data

output: content # Use the content folder as both the input and output directory of our build
