collections_config:
  posts:
    path: content/posts
    output: false # Tell CloudCannon to not assign output URLS to this collection, so that the `new_preview_url` is used instead
    new_preview_url: /previewer/ # Use the previewer page to preview all files in this collection
    _enabled_editors: # Prefer opening these files in the Visual Editor
      - visual
      - data

output: content # Use the content folder as both the input and output directory of our build
